
import os

MODERATOR_ID = 6828395702
ADMINS = set([MODERATOR_ID])
PHOTO_START = os.getenv("PHOTO_START")
PHOTO_RULES = os.getenv("PHOTO_RULES")
PHOTO_READY = os.getenv("PHOTO_READY")
PHOTO_FORM = os.getenv("PHOTO_FORM")
PHOTO_MENU = os.getenv("PHOTO_MENU")
PHOTO_BUILD_READY = os.getenv("PHOTO_BUILD_READY")
